dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotnev: .env
networks:
  # default: development
  rinkeby:
    eth_usd_price_feed: '0x71A3442B932563B8119be5ba6d547E5b6466688b'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}